#ifndef _CONFIG_H_
#define _CONFIG_H_

//#define CONFIG_SWSCALE
#define CONFIG_AVFILTER
#define CONFIG_AVDEVICE

#define CONFIG_AVUTIL "CONFIG_AVUTIL"
#define CONFIG_AVCODEC "CONFIG_AVCODEC"
#define CONFIG_AVFORMAT "CONFIG_AVFORMAT"
#define CONFIG_SWSCALE "CONFIG_SWSCALE"
#define CONFIG_SWRESAMPLE "CONFIG_SWRESAMPLE"

#endif
